# Generated by Django 6.0.4 on 2026-04-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Тип техники', 'verbose_name_plural': 'Типы техники'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Продана'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype', verbose_name='Тип техники'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hours_worked',
            field=models.PositiveIntegerField(verbose_name='Наработка (мото‑часов)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/Ставка'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
