# Generated by Django 6.0.4 on 2026-06-06 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_newequipmentnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newequipmentnotification',
            name='saved_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='equipment.savedsearch'),
        ),
    ]
