# Generated by Django 6.0.3 on 2026-06-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_chatmessage_equipment_and_more'),
        ('equipment', '0006_alter_newequipmentnotification_saved_search'),
    ]

    operations = [
    ]
