# Generated by Django 6.0.3 on 2026-06-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_merge_20260628_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newequipmentnotification',
            name='saved_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.savedsearch'),
        ),
    ]
