# Generated by Django 6.0.4 on 2026-04-12 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип техники')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], max_length=10, verbose_name='Категория')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('hours_worked', models.PositiveIntegerField(verbose_name='Наработка, мото‑часы')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена/Ставка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmenttype', verbose_name='Тип техники')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.region', verbose_name='Регион')),
            ],
        ),
    ]
